<?php

/**
 * High level object oriented filesystem abstraction.
 *
 * @package php-filesystem
 * @author  Tristan Lins <tristan.lins@bit3.de>
 * @link    http://bit3.de
 * @license http://www.gnu.org/licenses/lgpl-3.0.html LGPL
 */

namespace Bit3\Filesystem\Mountcontainer;

require_once(__DIR__ . '/../../../bootstrap.php');

use Bit3\Filesystem\FilesystemConfig;
use Bit3\Filesystem\Local\LocalFilesystem;
use Bit3\Filesystem\Local\LocalFilesystemConfig;
use Bit3\Filesystem\Iterator\FilesystemIterator;
use Bit3\Filesystem\Iterator\RecursiveFilesystemIterator;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-17 at 10:47:54.
 */
class MountcontainerFileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MergedFilesystem
     */
    protected $merged;

    /**
     * @var LocalFilesystem
     */
    protected $src;

	/**
	 * The source file from the source fs.
	 */
	protected $srcFile;

	/**
	 * The merged file.
	 */
	protected $mergedFile;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->merged = MountcontainerFilesystem::create(MountcontainerFilesystemConfig::create());
        $this->src = new LocalFilesystem(LocalFilesystemConfig::create(__DIR__ . '/../../../../src'));
        $this->merged->mount($this->src, '_test');

		$this->srcFile = $this->src->getFile('/Bit3/Filesystem/Merged/MergedFile.php');
		$this->mergedFile = $this->merged->getFile('/_test/Bit3/Filesystem/Merged/MergedFile.php');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Bit3\Filesystem\Mountcontainer\MountcontainerFile::getMD5
     */
    public function testExpectedClass()
    {
		$this->assertEquals('Bit3\Filesystem\Mountcontainer\MountcontainerFile', get_class($this->mergedFile));
    }

    /**
     * @covers Bit3\Filesystem\Mountcontainer\MountcontainerFile::getMD5
     */
    public function testMD5()
    {
		$this->assertEquals($this->srcFile->getMD5(), $this->mergedFile->getMD5());
    }

    /**
     * @covers Bit3\Filesystem\Mountcontainer\MountcontainerFile::getSHA1
     */
    public function testSHA1()
    {
		$this->assertEquals($this->srcFile->getSHA1(), $this->mergedFile->getSHA1());
    }

    /**
     * @covers Bit3\Filesystem\Mountcontainer\MountcontainerFile::getSHA1
     */
    public function testgetFileSystem()
    {
		$this->assertEquals($this->merged, $this->mergedFile->getFileSystem());
    }

	/**
	 * @covers Bit3\Filesystem\Mountcontainer\MountcontainerFile::getPathname
	 */
	public function testgetPathname()
	{
		$this->assertEquals('/_test/Bit3/Filesystem/Merged/MergedFile.php', $this->mergedFile->getPathname());
	}
}
